Repository jtr13/cc20, pull requests merged in 2020-11, with the labels that each got.

#3 Update project index
  index.Rmd
Labels: meta

#17 R selenium tutorial
  _bookdown.yml
  resources/rselenium_tutorial/Button.png
  resources/rselenium_tutorial/EDAV.PNG
  resources/rselenium_tutorial/Google.PNG
  resources/rselenium_tutorial/Initial.PNG
  resources/rselenium_tutorial/Inspect.PNG
  resources/rselenium_tutorial/Linkedin.PNG
  resources/rselenium_tutorial/Pagebutton.PNG
  resources/rselenium_tutorial/Select.PNG
  rselenium_tutorial.Rmd
Labels: web scraping

#50 Add chapters and update _bookdown.yml
  _bookdown.yml
Labels: meta

#26 Submit CC Likert_scale.Rmd for CC group 2
  likert_scale.Rmd
Labels: chap 3: data visualization, static viz

#74 Add chapter organization appendix
  R_data_transformation.Rmd
  _bookdown.yml
  appendix_chapter_organization.Rmd
  china_choropleth_map.Rmd
  pairs_and_ggpairs.Rmd
  tableau_intro_tutorial_demo_with_pset.Rmd
Labels: meta

#46 this is for Gaoyi Shi and Xiaonan Guo CC
  visualization_tools_in_real_work.Rmd
Labels: chap 4: results reporting, python, tableau

#20 Mosaic plot cheatsheet initial commit.
  Mosaic_plot_cheatsheet.Rmd
Labels: chap 7: cheatsheets/video tutorials

#83 Update _bookdown.yml
  _bookdown.yml
Labels: meta

#84 Benfords law
  _bookdown.yml
  benfords_law.Rmd
  resources/kent_county_benford_dist.png
  resources/kent_county_orders_of_magnitude_distribution.png
  resources/michigan_orders_of_magnitude_distribution.png
  resources/national_benford_dist.png
Labels: chap 5: complete analyses

#88 Add chapter headers and update _bookdown.yml
  Mosaic_plot_cheatsheet.Rmd
  _bookdown.yml
  rselenium_tutorial.Rmd
  visualization_tools_in_real_work.Rmd
Labels: meta

#18 Project of cc group 11
  .DS_Store
  _bookdown_files/.DS_Store
  _bookdown_files/cc20_files/.DS_Store
  data_visualization_in_python.Rmd
Labels: chap 6: other topics, python

#19 Add my community contribution: final_project_teammate_finder
  final_project_teammate_finder.Rmd
Labels: chap 6: other topics, community

#79 add my community contribution
  likert_data_cheatsheet.Rmd
Labels: chap 7: cheatsheets/video tutorials

#89 Rename Mosaic_plot_cheatsheet.Rmd to mosaic_plot_cheatsheet.Rmd
  mosaic_plot_cheatsheet.Rmd
Labels: meta

#90 Update _bookdown.yml
  _bookdown.yml
  r_data_transformation.Rmd
Labels: meta

#75 rmarkdown_tutorial_chinese_translation
  _bookdown.yml
  rmarkdown_tutorial_chinese_translation.rmd
Labels: chap 8: translation

#43 Adding datapipeline_design.Rmd file
  _bookdown.yml
  datapipeline_design.Rmd
Labels: chap 9: live tutorials

#65 add Network analysis introduction file
  Network_analysis_intro.Rmd
Labels: chap 9: live tutorials

#52 Speed_up_in_r_programming
  _bookdown.yml
  resources/speed_up_in_r_programming/autoSim.R
  resources/speed_up_in_r_programming/rpic.png
  resources/speed_up_in_r_programming/runsim.R
  speed_up_in_r_programming.Rmd
Labels: chap 6: other topics, r programming

#42 Automate EDA with data explorer
  _bookdown.yml
  automate_eda_with_dataexplorer.Rmd
  resources/automate_eda_with_dataexplorer/Unknown.png
Labels: chap 6: other topics, data analysis

#38 A basic Introduction to MCMC in R
  _bookdown.yml
  a_basic_introduction_to_mcmc_in_r.Rmd
Labels: chap 6: other topics, statistical computing

#62 add time series cheatsheet
  add_ts_cheatsheet.Rmd
Labels: chap 7: cheatsheets/video tutorials

#45 add community contribution from zc2489 which is focused on layout for…
  _bookdown.yml
  layout_for_baseplot_and_ggpplot.Rmd
Labels: chap 3: data visualization, static viz

#81 suggested datasets for the final project
  _bookdown.yml
  health_datasets_for_the_final_project.Rmd
Labels: chap 6: other topics, community

#58 Color in r
  _bookdown.yml
  color_in_r.Rmd
  resources/color_in_r/color_picker.png
  resources/color_in_r/dichromat.png
  resources/color_in_r/file.md
  resources/color_in_r/palette_viridis.png
Labels: chap 4: results reporting

#53 Adding group 9's Community contribution.
  _bookdown.yml
  a_simple_way_to_visualize_geographic_data.Rmd
Labels: chap 3: data visualization, static viz

#39 Create data_preprocessing_tutorial.Rmd
  _bookdown.yml
  data_preprocessing_tutorial.Rmd
Labels: chap 2: data processing and wrangling

#37 Geographical map packages
  _bookdown.yml
  geographical_map_packages.Rmd
  resources/geographical_map_packages/image1.jpg
Labels: chap 3: data visualization, static viz

#35 Haonan Wen - community contribution Rmd file
  _bookdown.yml
  label_setting_techniques.Rmd
Labels: chap 3: data visualization, static viz

#31 Create ggpubr_package.Rmd
  _bookdown.yml
  ggpubr_package.Rmd
Labels: chap 3: data visualization, static viz

#27 SQL in R
  Using_sql_in_R.Rmd
Labels: SQL, chap 6: other topics

#54 adding violinplot tutorial
  _bookdown.yml
  introduction_to_violin_plot.Rmd
Labels: chap 3: data visualization, static viz

#64 base_r_ggplot_graph
  _bookdown.yml
  base_r_ggplot_graph.Rmd
  mv.csv
Labels: chap 3: data visualization, static viz

#56 commit cc4 apply family
  _bookdown.yml
  apply_family.Rmd
Labels: chap 2: data processing and wrangling

#63 Radar Chart
  _bookdown.yml
  radar_chart.Rmd
Labels: chap 3: data visualization, pending, static viz

#34 python_vs_r_cheatsheet
  python_vs_r_cheatsheet.Rmd
Labels: chap 7: cheatsheets/video tutorials

#71 Adding CC chapter describing a trivia night that I hosted
  american_history_trivia_night.rmd
Labels: chap 9: live tutorials

#67 initial commit adding pdf
  categorical_cheat_sheet.rmd
  resources/categorical_cheat_sheet/categorical_cheat_sheet.pdf
Labels: chap 7: cheatsheets/video tutorials

#73 strayer cc
  _bookdown.yml
  consuming_terrorism_statistics.Rmd
Labels: chap 9: live tutorials

#22 Submission_Junzhi Ge and Yifei Zhang
  _bookdown.yml
  resources/visualization_nyc_covid19_rshiny/cc_1.png
  resources/visualization_nyc_covid19_rshiny/cc_2.png
  resources/visualization_nyc_covid19_rshiny/shiny.png
  visualization_nyc_covid19_rshiny.Rmd
Labels: chap 4: results reporting

#29 Cc among us project
  _bookdown.yml
  among_us_stats.Rmd
  resources/among_us_stats/among_us_player_stats.csv
Labels: chap 6: other topics, data analysis

#51 Added GeomMLBStadiums tutorial
  _bookdown.yml
  geommlbstadiums.rmd
Labels: chap 3: data visualization, static viz

#41 illustrated graphs in r group 27
  _bookdown.yml
  illustrate_graphs_in_r.Rmd
Labels: chap 3: data visualization, static viz

#70 cc_contribution upload
  _bookdown.yml
  resources/visualizing_electoral_margins/1976-2016-president.RData
  resources/visualizing_electoral_margins/turnout.xlsx
  visualizing_electoral_margins.Rmd
Labels: chap 5: complete analyses

#32 Weiyao Xie added community contribution: ipywidgets_tutorial.Rmd
  ipywidgets_tutorial.Rmd
Labels: chap 7: cheatsheets/video tutorials

#33 add interactive_choropleth_map project file
  interactive_choropleth_map.Rmd
Labels: chap 7: cheatsheets/video tutorials

#72 cc file upload
  _bookdown.yml
  chinese_tutorial_rvest_httr.Rmd
Labels: change requested, chap 8: translation

#69 Website sharing whole class mosaic plot translation
  _bookdown.yml
  resources/website_sharing_whole_class_mosaic_plot_translation/MusicIcecream.csv
  website_sharing_whole_class_mosaic_plot_translation.Rmd
Labels: chap 8: translation

#59 Better plotting with ggplot2 translated
  _bookdown.yml
  ggplot2_tutorial_translated.Rmd
Labels: chap 8: translation

#30 group 17 shiny_tutorial
  _bookdown.yml
  shiny_tutorial.Rmd
Labels: chap 4: results reporting

#55 update new file of cc-25-group (by Yihui hu)
  _bookdown.yml
  multivariate_grouped_data_plot.Rmd
Labels: change requested, chap 8: translation

#40 add cc .Rmd file to branch
  _bookdown.yml
  replication_crisis_psychology.Rmd
Labels: change requested, chap 7: cheatsheets/video tutorials
